config/routes.rb
Rails.application.routes.draw do
  root 'places#index'
  resources :places do
    resources :comments, only: :create
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :comments
  geocoded_by :address
  after_validation :geocode
  validates :address, presence: true

  validate :address_is_real
  after_commit :format_address
  def address_is_real
    return true if Geocoder.search(address)&.first&.formatted_address.present?

    errors.add(:address, "Not found")
  end
  def format_address
    return if Geocoder.search(address)&.first&.formatted_address == address

    update_columns(address: Geocoder.search(address)&.first&.formatted_address)

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def render_not_found(status=:not_found)
    render plain: "#{status.to_s.titleize} :(", status: status
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @place = Place.find_by_id(params[:place_id])
    return render_not_found if @place.blank?
    @place.comments.create(comment_params)
    redirect_to place_path(@place)
  end

  private

  

  def comment_params
    params.require(:comment).permit(:description, :user_name)
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index

    @q = Place.search(params[:q])
    @places = @q.result(distinct: true).paginate(page: params[:page], per_page: 10)
  end

  def show
    @place = Place.find_by_id(params[:id])
    if @place.blank?
      redirect_to new_place_path
    end
    @comment = Comment.new
  end

  def edit
    @place = Place.find_by_id(params[:id])
    if @place.blank?
      return render_not_found if @place.blank?
    end 
  end

  def update
    @place = Place.find_by_id(params[:id])
    return render_not_found if @place.blank?

    @place.update_attributes(place_params)

    if @place.valid?
      redirect_to root_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find_by_id(params[:id])
    return render_not_found if @place.blank?
    @place.destroy
    redirect_to root_path
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def place_params
    params.require(:place).permit(:name, :address)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anyplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'Anyplace', root_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
        <%= link_to new_place_path, class: 'nav-link' do %>
          <i class="fa fa-plus-circle"></i>
          New Place
        <% end %>
      </li>
    </ul>

    
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Place</h1>

  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/index.html.erb
<div class="booyah-box col-10 offset-1">
  <%= search_form_for @q do |f| %>
      <div class="field">
        <%= f.label :address_cont, "Search a place" %>
        <%= f.text_field :address_cont %>
      </div>
      
      <button class="actions btn btn-outline-success my-2 my-sm-0" id="click_address" type="submit" <%= f.submit %>>Search</button>
    </form>
  <% end %>
</div>

<% @places.each do |place| %>
  <div class="booyah-box col-10 offset-1">

    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <h1><%= link_to place.address, place_path(place) %></h1><br />
    <i><%= place.address %></i><br /><br />

    <% if place.comments.present? %>
      <div class="col-12">
        <blockquote>
          <%= place.comments.last.description %>
          <small><%= place.comments.last.user_name %></small>
        </blockquote>
      </div>
    <% end %>

  </div>

<% end %>

<%= will_paginate @places, renderer: BootstrapPagination::Rails, inner_window: 1, outer_window: 0 %>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <br />
    <%= f.submit "Create!", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-10 offset-1">
  <h1><%= @place.name %></h1>
  <i><%= @place.address %></i>
  <br/><br/>

  
    
  <% if @place.latitude.present? && @place.longitude.present? %>
  
    <script>

      function initMap() {
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: myLatLng
        });


        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>



    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDfp1WfZ6OdCspTF5DiermH68Zb0qqKhhQ&callback=initMap">
    </script>

    <div id="map"></div>
  <% end %>

  <br />


  <div class="float-right">
    <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
    <%= link_to 'Destroy', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
  </div>

  <div class="clear"></div>
  

  <br /><br />

  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
    Add a comment
  </button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
        </div>
        <div class="modal-body">
          <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
            <div class="modal-body">
              <%= f.input :description %>
              <%= f.input :user_name %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="clear"></div>
  <br />

    <h1>Comments</h1>
    <% @place.comments.each do |comment| %>
      <div class="col-12 col-sm-6">
        <blockquote>
          <b><%= comment.description %></b> -
          <small><%= comment.user_name %></small>
        </blockquote>
      </div>
    <% end %>


</div>